#!/usr/bin/env bash
# Copyright 2021-2023 GlitchyByte
# SPDX-License-Identifier: MIT-0

# Builds glib.

# [Setup]
set -u
# Capture caller directory and script directory.
readonly calling_dir="$(pwd)"
readonly script_dir="$(cd "$(dirname "$0")" && pwd)"
# Go to script directory and load utilities.
cd "${script_dir}"
. ./gscript

# [Main]
readonly project="glib"

# Define docs dir.
readonly docs_dir="${script_dir}/docs/${project}"

# Remove docs directory, if it exists.
if test -d "${docs_dir}"; then
  rm -dr "${docs_dir}"
  if test $? -ne 0; then
    echoerr "Can't remove '${docs_dir}'!"
    cd "${calling_dir}"
    exit 1
  fi
fi

# Clean, build, run tests, and generate javadocs.
cd "${script_dir}/code"
./gradlew :${project}:clean :${project}:build :${project}:javadoc
if test $? -ne 0; then
  echoerr "Failure!"
  cd "${calling_dir}"
  exit 1
fi

# Move javadocs to docs directory.
readonly javadoc_dir="${script_dir}/code/${project}/build/docs/javadoc"
mv "${javadoc_dir}" "${docs_dir}"

# Replace fonts.
sed -E \
  -e "s|^@import url\(.*\);|@import url('https://fonts.googleapis.com/css2?family=Exo+2\&family=JetBrains+Mono\&display=swap');|" \
  -e "s/'DejaVu (Sans|Serif)'/'Exo 2'/" \
  -e "s/'DejaVu Sans Mono'/'JetBrains Mono'/" \
  "${docs_dir}/stylesheet.css" > "${docs_dir}/tmp-sed"
mv "${docs_dir}/tmp-sed" "${docs_dir}/stylesheet.css"

# [Teardown]
cd "${calling_dir}"
