#!/usr/bin/env bash
# Copyright 2021-2022 GlitchyByte
# SPDX-License-Identifier: MIT-0

# Builds gpx.

# [Setup]
# Capture caller directory and script directory.
calling_dir="$(pwd)"
script_dir="$(cd "$(dirname "$0")" && pwd)"
# Go to script directory and load utilities.
cd "${script_dir}"
. ./gscript

# [Main]
project="gpx"

# Clean, build, and run tests.
cd "${script_dir}/code"
./gradlew :${project}:clean :${project}:build
if test $? -ne 0; then
  echoerr "Failure!"
  cd "${calling_dir}"
  exit 1
fi

cd "${calling_dir}"
