#!/usr/bin/env bash
# Copyright 2022-2023 GlitchyByte
# SPDX-License-Identifier: MIT-0

# Prints scripts description.

# [Setup]
set -u
# Capture caller directory and script directory.
readonly calling_dir="$(pwd)"
readonly script_dir="$(cd "$(dirname "$0")" && pwd)"
# Go to script directory and load utilities.
cd "${script_dir}"
. ./gscript

# [Main]
cd "${script_dir}"

echo "${cc_title}  ----[ glib ]----  ${c_reset}"
echo "${cc_item}  glib-build${cc_description}   Builds glib and generates javadocs.${c_reset}"
echo "${cc_item}  glib-publish${cc_description} Publishes glib artifact to public repository.${c_reset}"

echo "${cc_title}  ----[ gpx ]----  ${c_reset}"
echo "${cc_item}  gpx-build${cc_description} Builds gpx.${c_reset}"
echo "${cc_item}  gpx-make${cc_description}  Makes ${cc_highlight}run${cc_description} artifact.${c_reset}"

cd "${calling_dir}"
