#!/bin/sh
# Copyright 2022 GlitchyByte
# SPDX-License-Identifier: Apache-2.0

# Prepares the final details of this repository:
# - javadocs
# - run

# Capture caller directory and script directory.
calling_dir="$(pwd)"
script_dir="$(cd "$(dirname "$0")" && pwd)"

# Colors.
c_reset=$(tput sgr0)
c_bold=$(tput bold)
c_black=$(tput setaf 0)
c_red=$(tput setaf 1)
c_green=$(tput setaf 2)
c_yellow=$(tput setaf 3)
c_blue=$(tput setaf 4)
c_magenta=$(tput setaf 5)
c_cyan=$(tput setaf 6)
c_white=$(tput setaf 7)

# Echo to stderr.
echoerr() {
  >&2 echo "$@"
}

cd "${script_dir}"
./update-docs
./make-run
cd "${calling_dir}"
