#!/bin/sh
# Copyright 2021-2022 GlitchyByte
# SPDX-License-Identifier: Apache-2.0

# Update docs for GitHub.

# Capture caller directory and script directory.
calling_dir="$(pwd)"
script_dir="$(cd "$(dirname "$0")" && pwd)"

# Define docs dir.
docs_dir="docs"

# Remove docs directory, if it exists.
if test -d "$docs_dir"; then
  rm -dr "$docs_dir"
  if test $? -ne 0; then
    echo "Can't remove '$docs_dir'!"
    exit 1
  fi
fi

# Clean, run tests, and generate javadocs.
cd code || exit 1
./gradlew :glib:clean :glib:build :glib:javadoc
if test $? -ne 0; then
  echo "Tests failed!"
  cd "$calling_dir"
  exit 1
fi

# Move javadocs to docs directory.
cd "$calling_dir"
mv code/glib/build/docs/javadoc "$docs_dir"
