#!/usr/bin/env bash
# Copyright 2022-2023 GlitchyByte
# SPDX-License-Identifier: Apache-2.0

# Run app!
set -u

# Capture script directory.
readonly script_dir="$(cd "$(dirname "$0")" && pwd)"

# Capture gradle root.
readonly gradle_root=$1

# Capture project to run.
readonly project=$2

# Capture arguments.
shift
shift
readonly args=$*

# Build and get executable.
readonly gpx="${script_dir}/gpx.jar"
readonly executable="$(java -jar ${gpx} ${gradle_root} ${project})"

# Run app.
${executable} $args
